var viewModel =  {
    data : ko.observableArray([
        {id: 0, name: 'Картофельное пюре',fats: '6', proteins: '3', carbohydrate: '25',calories: '166', products: [0,1,8,9,6]},
        {id: 1, name: 'Грибной суп', fats:'5', proteins:'3', carbohydrate:'3', calories: '69', products: [10,1,2,6]},
        {id: 2, name: 'Гречневая каша', fats:'5', proteins:'11', carbohydrate:'62', calories: '337', products: [15,1,9,6]},
        {id: 3, name: 'Картофель фри', fats:'16', proteins:'3', carbohydrate:'34', calories: '292', products: [0,1,2]},
        {id: 4, name: 'Торт "Наполеон"', fats:'37', proteins:'8', carbohydrate:'42', calories: '533', products: [12,13,8,9]},
        {id: 5, name: 'Кофе с сахаром', fats:'0', proteins:'0', carbohydrate:'8', calories: '32', products: [11,14,6]},
        {id: 6, name: 'Куриные крылышки', fats:'24', proteins:'38', carbohydrate:'0', calories: '368', products: [7,1,2]},
        {id: 7, name: 'Чай с сахаром', fats:'0', proteins:'0', carbohydrate:'14', calories: '56', products: [6,16,14]},
        {id: 8, name: 'Рис вареный рассыпчастый', fats:'0', proteins:'4', carbohydrate:'49', calories: '212', products: [6,17,1,2,9]},
        {id: 9, name: 'Кекс с изюмом', fats:'12', proteins:'4', carbohydrate:'37', calories: '272', products: [12,13,14,6,22]},
        {id: 10, name: 'Легкие овощи', fats:'0', proteins:'1', carbohydrate:'14', calories: '60', products: [5,20,21]},
        {id: 11, name: 'Молочный шоколад', fats:'34', proteins:'9', carbohydrate:'50', calories: '542', products: [23]},
        {id: 12, name: 'Каша Булгур', fats:'0', proteins:'7', carbohydrate:'35', calories: '168', products: [6,19,1,2]},
        {id: 13, name: 'Борщ с мясом', fats:'0', proteins:'0', carbohydrate:'14', calories: '56', products: [6,20,21,4,1,2]},
        {id: 14, name: 'Мясо по французски', fats:'6', proteins:'3', carbohydrate:'20', calories: '146', products: [4,25,26,1,2]},
        {id: 15, name: 'Суп гороховый', fats:'7', proteins:'13', carbohydrate:'26', calories: '219', products: [1,2,6,27,4,21]},
        {id: 16, name: 'Блины', fats:'7', proteins:'3', carbohydrate:'15', calories: '135', products: [9,14,8,6,1]},
        {id: 17, name: 'Овсяная каша на молоке', fats:'10', proteins:'6', carbohydrate:'38', calories: '266', products: [28,14,8]},
        {id: 18, name: 'Овощное рагу', fats:'6', proteins:'2', carbohydrate:'15', calories: '122', products: [0,5,]},
        {id: 19, name: 'Солянка мясная', fats:'15', proteins:'13', carbohydrate:'6', calories: '197', products: [6,16,14]},
        {id: 20, name: 'Суп харчо', fats:'13', proteins:'9', carbohydrate:'16', calories: '217', products: [6,16,14]},
        {id: 21, name: 'Холодец из свинины', fats:'29', proteins:'24', carbohydrate:'2', calories: '365', products: [6,16,14]},
        {id: 22, name: 'Плов из свинины', fats:'60', proteins:'21', carbohydrate:'46', calories: '808', products: [6,16,14]},
        {id: 23, name: 'Отбивная из свинины', fats:'98', proteins:'22', carbohydrate:'0', calories: '970', products: [6,16,14]},
        {id: 24, name: 'Говядина тушеная', fats:'36', proteins:'33', carbohydrate:'0', calories: '456', products: [6,16,14]}
    ]),

    products : ko.observableArray([
        { id: 0, name: 'Картофель', enabled: ko.observable(true) },
        { id: 1, name: 'Соль', enabled: ko.observable(true) },
        { id: 2, name: "Перец", enabled: ko.observable(true) },
        { id: 3, name: "Печень", enabled: ko.observable(true) },
        { id: 4, name: "Свинина", enabled: ko.observable(true) },
        { id: 5, name: "Помидоры", enabled: ko.observable(true) },
        { id: 6, name: "Вода", enabled: ko.observable(true) },
        { id: 7, name: "Курица", enabled: ko.observable(true) },
        { id: 8, name: "Молоко", enabled: ko.observable(true) },
        { id: 9, name: "Масло", enabled: ko.observable(true) },
        { id: 10, name: "Грибы", enabled: ko.observable(true) },
        { id: 11, name: "Кофе", enabled: ko.observable(true) },
        { id: 12, name: "Мука", enabled: ko.observable(true) },
        { id: 13, name: "Яйца", enabled: ko.observable(true) },
        { id: 14, name: "Сахар", enabled: ko.observable(true) },
        { id: 15, name: "Гречневая крупа", enabled: ko.observable(true) },
        { id: 16, name: "Чай", enabled: ko.observable(true) },
        { id: 17, name: "Рис", enabled: ko.observable(true) },
        { id: 18, name: "Яйца", enabled: ko.observable(true) },
        { id: 19, name: "Булгур", enabled: ko.observable(true) },
        { id: 20, name: "Буряк", enabled: ko.observable(true) },
        { id: 21, name: "Морковь", enabled: ko.observable(true) },
        { id: 22, name: "Дрожжи", enabled: ko.observable(true) },
        { id: 23, name: "Шоколад", enabled: ko.observable(true) },
        { id: 24, name: "Красный перец", enabled: ko.observable(true) },
        { id: 25, name: "Сыр", enabled: ko.observable(true) },
        { id: 26, name: "Лук", enabled: ko.observable(true) },
        { id: 27, name: "Горох", enabled: ko.observable(true) },
        { id: 25, name: "Овсянка", enabled: ko.observable(true) },
    ])


};